---
- hosts: servers
  vars:
    package_names:
      - vim
  tasks:
    - name: "Check if listed package is installed or not on Debian Linux family"
      command: dpkg-query -l "{{ item }}"
      loop: "{{ package_names }}"
      register: package_check
      when: ansible_facts['os_family'] == "Debian"

    - name: "Check if listed package is installed or not on Red Hat Linux family"
      command: rpm -q "{{ item }}"
      loop: "{{ package_names }}"
      register: package_check
      when: ansible_facts['os_family'] == "RedHat"
    - name: "Print execution results"
      debug:
        msg: "Package is installed"
      when: package_check is succeeded
      
  tasks:
  - name: Check is docer-compose installed
    shell: command -v docker-compose >/dev/null 2>&1
    register: is_docker_compose_install
    ignore_errors: yes
  
  - debug: msg="{{ is_docker_compose_install.rc }}" # it returns rc 0 if installed or 127 if not
  - debug: var=is_docker_compose_install
