---
# CentOS 7 LAMP Stack
# Author: Arockiasamy K
# Version: 1.0

- name: Apply for common configuration to all the nodes
  hosts: webservers
  become: root

   
- name: deploy MySQL and configure databases
  hosts: dbservers
  become: yes
   
   
- name: deploy Apache, PHP and configure website code
  hosts: webservers
  become: yes
   
