---
# CentOS 7 LAMP Stack
# Author: Arockiasamy K
# Version: 1.0

- name: Apply for common configuration to all the nodes
  hosts: all
  become: root

  roles:
   - common
   
- name: deploy MySQL and configure databases
  hosts: dbservers
  become: yes
   
  roles:
   - db
   
- name: deploy Apache, PHP and configure website code
  hosts: webservers
  become: yes
   
  roles:
   - web
